-- [코드 흐름 요약]
-- 1) pgvector 확장을 설치한다.
-- 2) Hibernate가 이후에 vector(768) 컬럼을 포함한 테이블을 생성할 수 있게 준비한다.
CREATE EXTENSION IF NOT EXISTS vector;

-- age_theme 테이블
CREATE TABLE IF NOT EXISTS age_theme (
                                         id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         min_age   INT NOT NULL,
                                         max_age   INT NOT NULL,
                                         category  VARCHAR(32) NOT NULL,
    theme     TEXT NOT NULL,
    embedding BYTEA NULL,
    CHECK (min_age >= 0 AND max_age >= min_age)
    );

-- vocab_term 테이블
CREATE TABLE IF NOT EXISTS vocab_term (
                                          id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          term      VARCHAR(128) NOT NULL UNIQUE,
    embedding BYTEA NULL
    );