-- ==============================================
-- pgvector 기반 node_snippet 테이블 생성
-- ==============================================

-- 1. pgvector extension 활성화
-- 이미 활성화 되어 있을 수 있으므로 IF NOT EXISTS 사용
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. node_snippet 테이블 생성
CREATE TABLE IF NOT EXISTS node_snippet (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id   BIGINT NOT NULL,
    age_year  INT    NOT NULL,
    category  VARCHAR(50),
    text      TEXT   NOT NULL,
    embedding VECTOR(768) NOT NULL
);

-- 3. 검색 성능을 위한 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_node_snippet_line_age
    ON node_snippet(line_id, age_year);

-- 코사인 거리 기반 KNN 인덱스 생성
-- hnsw 인덱스 성능이 좋지만 db.t3.micro 상 메모리 문제로 인해 ivfflat 사용
CREATE INDEX IF NOT EXISTS idx_node_snippet_embedding_ivfflat
    ON node_snippet USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 50)