/*
 * 이 파일은 pgvector 기반 검색 테이블을 한 번에 생성한다.
 * 흐름: 확장 활성화 → age_theme 생성/인덱스 → vocab_term 생성/인덱스 → ANALYZE
 */

-- 확장 활성화
CREATE EXTENSION IF NOT EXISTS vector;

-- age_theme 테이블 생성
CREATE TABLE IF NOT EXISTS age_theme (
                                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         min_age    INT NOT NULL,
                                         max_age    INT NOT NULL,
                                         category   VARCHAR(32) NOT NULL,
    theme      TEXT NOT NULL,
    embedding  VECTOR(768) NOT NULL,
    -- 무결성 검증
    CONSTRAINT ck_age_theme_age_range CHECK (min_age >= 0 AND max_age >= min_age)
    );

-- 범주/연령대 필터 인덱스
CREATE INDEX IF NOT EXISTS idx_age_theme_cat_age
    ON age_theme(category, min_age, max_age);

-- 코사인 KNN 인덱스(저사양 환경 고려 ivfflat)
CREATE INDEX IF NOT EXISTS idx_age_theme_embedding_ivfflat
    ON age_theme USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 50);

-- vocab_term 테이블 생성
CREATE TABLE IF NOT EXISTS vocab_term (
                                          id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          term       VARCHAR(128) NOT NULL UNIQUE,
    embedding  VECTOR(768) NOT NULL
    );

-- 코사인 KNN 인덱스
CREATE INDEX IF NOT EXISTS idx_vocab_term_embedding_ivfflat
    ON vocab_term USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 50);

-- 통계 수집
ANALYZE age_theme;
ANALYZE vocab_term;
