/*
 * 이 파일은 pgvector 기반 실서비스용 스키마를 생성한다.
 * 흐름: 확장 활성화 → age_theme(제약/인덱스) → vocab_term(제약/인덱스) → ANALYZE
 */

-- next 확장 활성화
CREATE EXTENSION IF NOT EXISTS vector;

-- next age_theme 테이블 생성
CREATE TABLE IF NOT EXISTS age_theme (
                                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         min_age    INT NOT NULL,
                                         max_age    INT NOT NULL,
                                         category   VARCHAR(32) NOT NULL
    CHECK (category IN ('EDUCATION','CAREER','RELATIONSHIP','FINANCE','HEALTH','LOCATION','ETC')),
    theme      TEXT NOT NULL,
    embedding  VECTOR(768) NOT NULL,
    -- 무결성 검증
    CHECK (min_age >= 0 AND max_age >= min_age)
    );

-- next 범주/연령대 필터 인덱스
CREATE INDEX IF NOT EXISTS idx_age_theme_cat_age
    ON age_theme(category, min_age, max_age);

-- next 코사인 KNN 인덱스(저사양 고려 ivfflat)
CREATE INDEX IF NOT EXISTS idx_age_theme_embedding_ivfflat
    ON age_theme USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 50);

-- next vocab_term 테이블 생성 (term 유니크)
CREATE TABLE IF NOT EXISTS vocab_term (
                                          id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          term       VARCHAR(128) NOT NULL UNIQUE,
    embedding  VECTOR(768) NOT NULL
    );

-- next 코사인 KNN 인덱스
CREATE INDEX IF NOT EXISTS idx_vocab_term_embedding_ivfflat
    ON vocab_term USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 50);

-- next 통계 수집(IVFFLAT 생성 후 권장)
ANALYZE age_theme;
ANALYZE vocab_term;

/*
-- 옵션: 메모리 여유 & PG ≥ 16이면 HNSW 사용
-- CREATE INDEX IF NOT EXISTS idx_age_theme_embedding_hnsw
--   ON age_theme USING hnsw (embedding vector_cosine_ops);
-- CREATE INDEX IF NOT EXISTS idx_vocab_term_embedding_hnsw
--   ON vocab_term USING hnsw (embedding vector_cosine_ops);
*/
