spring:
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:db_test;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console