name: 'Setup Backend Environment'
description: 'Setup JDK 21 and caching Gradle dependencies'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'graalvm'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-